[package]
name = "sfwm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11rb = { version = "0.9.0", features = ["all-extensions"] } 
xmodmap-pke = "0.2.3"
